# Spring
spring.application.name=service-actor
# Dubbo
dubbo.application.name=dubbo-service-actor
dubbo.application.qos-enable=false
# Registry
dubbo.registry.group = actor-server
dubbo.registry.address=zookeeper://localhost:2181
dubbo.consumer.timeout=3000
dubbo.consumer.retries=0
dubbo.consumer.check=false
dubbo.consumer.router=fixedRouter
# Protocol
dubbo.protocol.name=tri
dubbo.protocol.port=50051
dubbo.protocol.serialization=protobuf
# Provider
dubbo.provider.timeout=5000
dubbo.provider.retries=0
dubbo.provider.threadpool=cached
dubbo.provider.threads=200
dubbo.provider.accepts=1000

#spring.redis.host=127.0.0.1
#spring.redis.port=6379
#spring.redis.timeout=1000
#spring.redis.connect-timeout=1000

akka.actor.provider=local
akka.remote.artery.enabled=false
akka.cluster.enabled=false
akka.actor.default-dispatcher.executor=fork-join-executor
akka.actor.default-dispatcher.fork-join-executor.parallelism-min=4
akka.actor.default-dispatcher.fork-join-executor.parallelism-factor=1.0
akka.actor.default-dispatcher.fork-join-executor.parallelism-max=8
akka.actor.default-dispatcher.throughput=5
