# Spring
spring.application.name=gateway-service
# Netty
netty.serverId=1
netty.server.ip=0.0.0.0
netty.server.port=6656
netty.server.worker-size=100
netty.server.shutdown-waitSeconds=30
netty.server.maxFrameLength=65536
# Dubbo
dubbo.application.name=dubbo-gateway-service
dubbo.application.qos-enable=false
# Registry
dubbo.registry.group = actor-server
dubbo.registry.address=zookeeper://localhost:2181
dubbo.consumer.timeout=3000
dubbo.consumer.retries=2
dubbo.consumer.check=false
dubbo.consumer.router=fixedRouter
dubbo.consumer.cluster=failover
# Protocol
dubbo.protocol.name=tri
dubbo.protocol.serialization=protobuf
# Provider
dubbo.provider.timeout=5000
dubbo.provider.retries=0
dubbo.provider.threadpool=cached
dubbo.provider.threads=200
dubbo.provider.accepts=1000

#spring.redis.host=127.0.0.1
#spring.redis.port=6379
#spring.redis.timeout=1000
#spring.redis.connect-timeout=1000

akka.actor.provider=local
akka.remote.artery.enabled=false
akka.cluster.enabled=false
akka.actor.default-dispatcher.executor=thread-pool-executor
akka.actor.default-dispatcher.thread-pool-executor.core-pool-size-min=64
akka.actor.default-dispatcher.thread-pool-executor.core-pool-size-factor=1.0
akka.actor.default-dispatcher.thread-pool-executor.core-pool-size-max=64
akka.actor.default-dispatcher.thread-pool-executor.max-pool-size=128
akka.actor.default-dispatcher.thread-pool-executor.keep-alive-time=60s
akka.actor.default-dispatcher.throughput=5
